apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-16-1-1
  namespace: simulation
  labels:
    app: nextjs-16-1-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-16-1-1
  template:
    metadata:
      labels:
        app: nextjs-16-1-1
    spec:
      containers:
      - name: nextjs
        image: nextjs:16.1.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
