apiVersion: v1
kind: Service
metadata:
  name: money-pos-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: money-pos-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: money-pos-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: money-pos-redis
---
apiVersion: v1
kind: Service
metadata:
  name: xxl-job-admin
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
  selector:
    app: xxl-job-admin
---
apiVersion: v1
kind: Service
metadata:
  name: money-pos
spec:
  type: NodePort
  ports:
    - port: 9101
      targetPort: 9101
      nodePort: 30002
  selector:
    app: money-app-biz
