apiVersion: v1
kind: Pod
metadata:
  name: cve-2025-55182
  namespace: simulation
  labels:
    app: cve-2025-55182-react2shell
spec:
  containers:
  - name: cve-2025-55182-react2shell
    image: ghcr.io/s2n0n/c2z/cve-2025-55182-react2shell:latest
    ports:
    - containerPort: 3005
      name: http