apiVersion: v1
kind: Service
metadata:
  name: cve-2025-55182-nx16
  namespace: simulation
spec:
  selector:
    app: cve-2025-55182-nx16
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
