apiVersion: v1
kind: Pod
metadata:
  name: cve-2025-55182-nx16
  namespace: simulation
  labels:
    app: cve-2025-55182-nx16
spec:
  imagePullSecrets:
  - name: ghcr-secret
  containers:
  - name: cve-2025-55182-nx16
    image: ghcr.io/s2n0n/c2z/cve-2025-55182-next-js-16:latest
    ports:
    - containerPort: 3005
      name: http