apiVersion: v1
kind: Pod
metadata:
  name: cve-2025-63531
  namespace: simulation
  labels:
    app: cve-2025-63531
spec:
  imagePullSecrets:
    - name: ghcr-secret
  containers:
  - name: cve-2025-63531
    image: ghcr.io/s2n0n/c2z/sqlinjection-blood-bank:latest
    ports:
    - containerPort: 80