apiVersion: v1
kind: Service
metadata:
  name: nextjs-16-1-1
  namespace: simulation
spec:
  selector:
    app: nextjs-16-1-1
  ports:
  - protocol: TCP
    port: 80           # 외부 접속 포트
    targetPort: 3000   # 내부 연결 포트
