apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kali-tools-pvc
  namespace: attacker-zone
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.attacker.kali.persistence.size }}
  storageClassName: local-path
