apiVersion: v1
kind: Service
metadata:
  name: kali
  namespace: attacker-zone
spec:
  type: ClusterIP
  selector:
    app: kali
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 4444
    name: metasploit
    targetPort: 4444
